GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todos
Content-Type: application/json

{
	"text": "Pick up boat"
}

###

DELETE http://localhost:3001/todo/60e585eb6177f95ff0574326

###

GET http://localhost:3001/todo/60e585d86177f95ff0574323/toggle-completion

###

PUT http://localhost:3001/todo/60e585d86177f95ff0574323
Content-Type: application/json

{
	"text": "Go Shopping for Milk"
}